Obras
DadosAbertosDeFeira/tcm-ba pull request #26
Opened 2021-06-16 01:46 UTC by RaulBSantos

Cria spider para coletar obras de município #9

2021-06-16 19:43 UTC, anapaulagomes reviewed
Muito bom, @RaulBSantos! 👏🏽  Curiosa: a data mais antiga é 2018? Rodei aqui e só retornou 7 obras. É isso mesmo?

@Laerte se tiver um tempo, dá uma olhadinha?

2021-06-16 19:43 UTC, anapaulagomes commented on tcmba/spiders/obras.py
> +        super(ConstructionsSpider, self).__init__(*args, **kwargs)
```suggestion
        super().__init__(*args, **kwargs)
```

2021-06-16 19:43 UTC, anapaulagomes commented on tcmba/spiders/obras.py
> +                    "name": company_content.re_first(r"<td>(\D+)</td>"),
Aqui tu poderia pegar pegar a coluna usando o css path também:

```suggestion
                    "name": company_content.css("td"),
```

2021-06-16 19:43 UTC, anapaulagomes commented on tcmba/spiders/obras.py
> +            company_content = row.css("a.btn-popover::attr(data-content)")
```suggestion
            company_content = row.css("a.btn-popover::attr(data-content) td")
```

```suggestion
                    "name": company_content.re_first(r"\D+"),
```

E aí fazer o match. Seria mais seguro pra dar match com as colunas.

2021-06-16 21:00 UTC, Laerte requested changes

2021-06-16 21:12 UTC, anapaulagomes commented on tcmba/spiders/obras.py
> +    url = "https://www.tcm.ba.gov.br/portal-da-cidadania/obras/?municipio=2910800"
Seria legal ter isso parametrizado mesmo!

2021-06-24 01:20 UTC, RaulBSantos commented on tcmba/spiders/obras.py
> +        super(ConstructionsSpider, self).__init__(*args, **kwargs)
Valeu @anapaulagomes! 
Então, pelo que vi no site, a partir de 2006 já é para retornar dados, são 315 obras.  Em 2018 é pra ter 93 obras, mas rodando aqui deu 92. Pulou a 62-2018, estou vendo se deu algum bug.

2021-06-24 01:33 UTC, RaulBSantos commented on tcmba/spiders/obras.py
> +            url = f"{self.url}&ano={year}&entidade=129&pesquisar=Pesquisar"
> Muito bom, @RaulBSantos! 👏🏽 Curiosa: a data mais antiga é 2018? Rodei aqui e só retornou 7 obras. É isso mesmo?
> 
> @Laerte se tiver um tempo, dá uma olhadinha?

Valeu @anapaulagomes!
Então, pelo que vi no site, a partir de 2006 já é para retornar dados, são 315 obras. Em 2018 é pra ter 93 obras, mas rodando aqui deu 92. Pulou a 62-2018, estou vendo se deu algum bug.

2021-06-24 01:35 UTC, RaulBSantos commented on tcmba/spiders/obras.py
> +        super(ConstructionsSpider, self).__init__(*args, **kwargs)
> Muito bom, @RaulBSantos! 👏🏽 Curiosa: a data mais antiga é 2018? Rodei aqui e só retornou 7 obras. É isso mesmo?
> 
> @Laerte se tiver um tempo, dá uma olhadinha?

Valeu @anapaulagomes!
Então, pelo que vi no site, a partir de 2006 já é para retornar dados, são 315 obras. Em 2018 é pra ter 93 obras, mas rodando aqui deu 92. Pulou a 62-2018, estou vendo se deu algum bug.

2021-06-24 01:36 UTC, RaulBSantos commented
> Muito bom, @RaulBSantos! 👏🏽 Curiosa: a data mais antiga é 2018? Rodei aqui e só retornou 7 obras. É isso mesmo?
> 
> @Laerte se tiver um tempo, dá uma olhadinha?

Valeu @anapaulagomes!
Então, pelo que vi no site, a partir de 2006 já é para retornar dados, são 315 obras. Em 2018 é pra ter 93 obras, mas rodando aqui deu 92. Pulou a 62-2018, estou vendo se deu algum bug.

2021-09-22 07:50 UTC, anapaulagomes commented
Alô, @RaulBSantos! Precisa de alguma ajuda aqui?

2021-09-22 17:15 UTC, RaulBSantos commented
Acho que vou precisar sim pra ver o bug. Vou subir as alterações do PR, e testar pra ver porque deu essa diferença de quantidade.

2021-09-23 08:55 UTC, anapaulagomes commented
Pronto, manda aí e a gente combina pra vermos juntos! @RaulBSantos

2021-09-26 23:02 UTC, RaulBSantos commented
> Pronto, manda aí e a gente combina pra vermos juntos! @RaulBSantos

@anapaulagomes, a página do TCM está com algum erro. Não está dando pra testar o Crawler :( 

Onde podemos contatar pra eles resolverem?

![tcm-obras-erro](https://user-images.githubusercontent.com/14143674/134827096-e8652fb6-89a4-467b-ba4b-65d9d6dc89ab.png)

2021-09-27 07:48 UTC, anapaulagomes commented
Alô, @RaulBSantos. Testei aqui no Firefox e no Chrome e nos dois não está funcionando mesmo. No Chrome nem carrega. Pode, por favor, enviar um email para  dti@tcm.ba.gov.br e atendimento.etcm@tcm.ba.gov.br com cópia para o email do dados?

2021-09-30 11:51 UTC, RaulBSantos commented
> Alô, @RaulBSantos. Testei aqui no Firefox e no Chrome e nos dois não está funcionando mesmo. No Chrome nem carrega. Pode, por favor, enviar um email para [dti@tcm.ba.gov.br](mailto:dti@tcm.ba.gov.br) e [atendimento.etcm@tcm.ba.gov.br](mailto:atendimento.etcm@tcm.ba.gov.br) com cópia para o email do dados?

já voltou a funcionar

2021-09-30 16:56 UTC, anapaulagomes commented
Massa! Se quiser sobe as alterações da revisão e eu dou uma olhada no bug. @RaulBSantos

2021-10-02 13:37 UTC, RaulBSantos commented on tcmba/spiders/obras.py
> +            company_content = row.css("a.btn-popover::attr(data-content)")
Nesse ponto, não sei se vai funcionar.. Pois este conteúdo está como um data-content dentro da tag <a>. É usado no popover do Bootstrap

![image](https://user-images.githubusercontent.com/14143674/135718758-45563d2f-13ba-4522-8ced-2f2d9f046844.png)

2021-10-02 15:00 UTC, RaulBSantos commented on tcmba/spiders/obras.py
> +            company_content = row.css("a.btn-popover::attr(data-content)")
resolvido com o help da Ana

![image](https://user-images.githubusercontent.com/14143674/135722096-49c94a1a-a3c5-44e5-a8b2-1035783f6113.png)

2021-10-03 14:58 UTC, anapaulagomes commented
Em 2021 a página diz ter 18 obras. Falta a número 12-2021 (seguindo a sequência da página).
https://www.tcm.ba.gov.br/portal-da-cidadania/obras/?municipio=2910800&entidade=129&ano=2021&dsObra=&dtlObra=&empresaObra=&stObra=&pesquisar=Pesquisar&pesquisar=Pesquisar

No crawler está faltando a 16-2021. Ao olhar no log, vejo esse erro:

```
2021-10-03 16:43:07 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.tcm.ba.gov.br/detalhes-da-obra-servico/?cdLicitacao=&cdEntidade=129&entidadeTexto=&nuAno=2021&cdObra=16-2021> (referer: https://www.tcm.ba.gov.br/portal-da-cidadania/obras/?municipio=2910800&ano=2021&entidade=129&pesquisar=Pesquisar)
Traceback (most recent call last):
  File "/home/ana/.local/lib/python3.8/site-packages/scrapy/utils/defer.py", line 120, in iter_errback
    yield next(it)
  File "/home/ana/.local/lib/python3.8/site-packages/scrapy/utils/python.py", line 353, in __next__
    return next(self.data)
  File "/home/ana/.local/lib/python3.8/site-packages/scrapy/utils/python.py", line 353, in __next__
    return next(self.data)
  File "/home/ana/.local/lib/python3.8/site-packages/scrapy/core/spidermw.py", line 62, in _evaluate_iterable
    for r in iterable:
  File "/home/ana/.local/lib/python3.8/site-packages/scrapy/spidermiddlewares/offsite.py", line 29, in process_spider_output
    for x in result:
  File "/home/ana/.local/lib/python3.8/site-packages/scrapy/core/spidermw.py", line 62, in _evaluate_iterable
    for r in iterable:
  File "/home/ana/.local/lib/python3.8/site-packages/scrapy/spidermiddlewares/referer.py", line 340, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "/home/ana/.local/lib/python3.8/site-packages/scrapy/core/spidermw.py", line 62, in _evaluate_iterable
    for r in iterable:
  File "/home/ana/.local/lib/python3.8/site-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/home/ana/.local/lib/python3.8/site-packages/scrapy/core/spidermw.py", line 62, in _evaluate_iterable
    for r in iterable:
  File "/home/ana/.local/lib/python3.8/site-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/home/ana/.local/lib/python3.8/site-packages/scrapy/core/spidermw.py", line 62, in _evaluate_iterable
    for r in iterable:
  File "/home/ana/workspace/tcm-ba/tcmba/spiders/obras.py", line 71, in parse_details
    item["competence"] = values[3]
IndexError: list index out of range
```

Essa obra parece ter poucos detalhes: https://www.tcm.ba.gov.br/detalhes-da-obra-servico/?cdLicitacao=&cdEntidade=129&entidadeTexto=&nuAno=2021&cdObra=16-2021. Talvez ela tenha só o mínimo mesmo. :/ Agora é checar se a lista tem o tamanho mínimo pra cada campo.

```
item["competence"] = values[3] if len(values) >= 3 else ""
```

2021-10-03 22:36 UTC, RaulBSantos commented
> Em 2021 a página diz ter 18 obras. Falta a número 12-2021 (seguindo a sequência da página). https://www.tcm.ba.gov.br/portal-da-cidadania/obras/?municipio=2910800&entidade=129&ano=2021&dsObra=&dtlObra=&empresaObra=&stObra=&pesquisar=Pesquisar&pesquisar=Pesquisar
> 
> No crawler está faltando a 16-2021. Ao olhar no log, vejo esse erro:
> 
> ```
> 2021-10-03 16:43:07 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.tcm.ba.gov.br/detalhes-da-obra-servico/?cdLicitacao=&cdEntidade=129&entidadeTexto=&nuAno=2021&cdObra=16-2021> (referer: https://www.tcm.ba.gov.br/portal-da-cidadania/obras/?municipio=2910800&ano=2021&entidade=129&pesquisar=Pesquisar)
> Traceback (most recent call last):
>   File "/home/ana/.local/lib/python3.8/site-packages/scrapy/utils/defer.py", line 120, in iter_errback
>     yield next(it)
>   File "/home/ana/.local/lib/python3.8/site-packages/scrapy/utils/python.py", line 353, in __next__
>     return next(self.data)
>   File "/home/ana/.local/lib/python3.8/site-packages/scrapy/utils/python.py", line 353, in __next__
>     return next(self.data)
>   File "/home/ana/.local/lib/python3.8/site-packages/scrapy/core/spidermw.py", line 62, in _evaluate_iterable
>     for r in iterable:
>   File "/home/ana/.local/lib/python3.8/site-packages/scrapy/spidermiddlewares/offsite.py", line 29, in process_spider_output
>     for x in result:
>   File "/home/ana/.local/lib/python3.8/site-packages/scrapy/core/spidermw.py", line 62, in _evaluate_iterable
>     for r in iterable:
>   File "/home/ana/.local/lib/python3.8/site-packages/scrapy/spidermiddlewares/referer.py", line 340, in <genexpr>
>     return (_set_referer(r) for r in result or ())
>   File "/home/ana/.local/lib/python3.8/site-packages/scrapy/core/spidermw.py", line 62, in _evaluate_iterable
>     for r in iterable:
>   File "/home/ana/.local/lib/python3.8/site-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
>     return (r for r in result or () if _filter(r))
>   File "/home/ana/.local/lib/python3.8/site-packages/scrapy/core/spidermw.py", line 62, in _evaluate_iterable
>     for r in iterable:
>   File "/home/ana/.local/lib/python3.8/site-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr>
>     return (r for r in result or () if _filter(r))
>   File "/home/ana/.local/lib/python3.8/site-packages/scrapy/core/spidermw.py", line 62, in _evaluate_iterable
>     for r in iterable:
>   File "/home/ana/workspace/tcm-ba/tcmba/spiders/obras.py", line 71, in parse_details
>     item["competence"] = values[3]
> IndexError: list index out of range
> ```
> 
> Essa obra parece ter poucos detalhes: https://www.tcm.ba.gov.br/detalhes-da-obra-servico/?cdLicitacao=&cdEntidade=129&entidadeTexto=&nuAno=2021&cdObra=16-2021. Talvez ela tenha só o mínimo mesmo. :/ Agora é checar se a lista tem o tamanho mínimo pra cada campo.
> 
> ```
> item["competence"] = values[3] if len(values) >= 3 else ""
> ```

Essa parte da implementação não ficou legal, como estou pegando por ordem, pode ser que fique errado. Estou melhorando para buscar por termo. Ex:

`item["source"] = response.css(".form-group").xpath(".//span[preceding-sibling::label[contains(., 'Fonte')]]").get()`

2021-10-04 00:04 UTC, Laerte commented on tcmba/spiders/obras.py
> +        response.css(".form-group")
Nós precisamos desse seletor? Testei no site e apenas o xpath já funciona.

2021-10-04 00:06 UTC, Laerte commented on tcmba/spiders/obras.py
> +    return value if value else ""
```suggestion
    return value or ""
```
Você pode simplificar aqui.

2021-10-04 00:32 UTC, RaulBSantos commented on tcmba/spiders/obras.py
> +        response.css(".form-group")
Boa! Realmente não precisa mais

2021-10-04 00:32 UTC, Laerte commented on tcmba/spiders/obras.py
> +            year += 1
```suggestion
        for year in range(year, self.current_year + 1):
            url = f"{self.url}?municipio={self.cidade}&ano={year}&entidade={self.entidade}&pesquisar=Pesquisar"
```
Nitpicking. 🧙🏻‍♂️

2021-10-04 00:43 UTC, Laerte approved these changes
Ótimo trabalho. Parabéns! 🎉

2021-10-04 00:45 UTC, RaulBSantos commented
> Ótimo trabalho. Parabéns! tada

Valeu! Obrigado pela ajuda!

2021-10-07 11:21 UTC, Laerte commented
@anapaulagomes Podemos mergear?

2021-10-07 12:29 UTC, anapaulagomes commented
Tô de férias, não tinha visto as alterações haha simbora!

2021-10-07 12:29 UTC, merged